// GENERADO por packages/tokens/scripts/generar.mjs. No editar a mano.
export const base = {
  "espacio-1": "4px",
  "espacio-2": "8px",
  "espacio-3": "12px",
  "espacio-4": "16px",
  "espacio-5": "24px",
  "espacio-6": "32px",
  "espacio-7": "48px",
  "radio-sm": "4px",
  "radio-md": "8px",
  "radio-lg": "12px",
  "fuente-sistema": "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
  "fuente-mono": "ui-monospace, \"SF Mono\", Menlo, Consolas, monospace",
  "texto-xs": "12px",
  "texto-sm": "13px",
  "texto-md": "14px",
  "texto-lg": "16px",
  "texto-xl": "20px",
  "texto-2xl": "24px",
  "interlineado-xs": "16px",
  "interlineado-sm": "20px",
  "interlineado-md": "20px",
  "interlineado-lg": "24px",
  "interlineado-xl": "28px",
  "interlineado-2xl": "32px",
  "tactil-web": "24px",
  "tactil-movil": "48px",
  "tactil-movil-principal": "56px",
  "fila-web": "36px",
  "fila-movil": "56px",
  "sombra-sm": "0 1px 2px rgba(11, 30, 43, 0.12)",
  "sombra-md": "0 4px 12px rgba(11, 30, 43, 0.16)",
  "sombra-lg": "0 12px 32px rgba(11, 30, 43, 0.24)"
} as const;

export const temas = {
  claro: {
      "fondo": "#F5F4F0",
      "superficie": "#FFFFFF",
      "texto": "#1B2A36",
      "texto-secundario": "#5B6873",
      "primario": "#004B72",
      "primario-hover": "#0A7A86",
      "primario-texto": "#FFFFFF",
      "acento": "#00C9A7",
      "exito-texto": "#1A7F45",
      "exito-relleno": "#2ECC71",
      "exito-relleno-texto": "#1B2A36",
      "advertencia-texto": "#8F5F12",
      "advertencia-relleno": "#E0A93B",
      "advertencia-relleno-texto": "#1B2A36",
      "error": "#C53030",
      "error-texto": "#FFFFFF",
      "borde-campo": "#7C8993",
      "borde-suave": "#DDE2E6",
      "foco": "#004B72",
      "foco-halo": "#00C9A7",
      "decorativo-advertencia": "#B7791F",
      "decorativo-borde": "#A2ADB5",
      "chip-neutro-texto": "#3F4D59",
      "chip-neutro-fondo": "#E6E9EC",
      "chip-curso-texto": "#004B72",
      "chip-curso-fondo": "#DCEBF4",
      "chip-cerrada-texto": "#17703E",
      "chip-cerrada-fondo": "#DDF3E5",
      "chip-riesgo-texto": "#8F5F12",
      "chip-riesgo-fondo": "#FBEFD3",
      "chip-vencida-texto": "#A92A2A",
      "chip-vencida-fondo": "#FBE3E3",
      "velo": "rgba(11, 30, 43, 0.6)"
  },
  oscuro: {
      "fondo": "#0B1E2B",
      "superficie": "#12293A",
      "texto": "#E8EEF2",
      "texto-secundario": "#A9B7C2",
      "primario": "#4A9FCF",
      "primario-hover": "#6DB3DD",
      "primario-texto": "#0B1E2B",
      "acento": "#00C9A7",
      "exito-texto": "#4ADE80",
      "exito-relleno": "#2ECC71",
      "exito-relleno-texto": "#0B1E2B",
      "advertencia-texto": "#E6B04A",
      "advertencia-relleno": "#E6B04A",
      "advertencia-relleno-texto": "#0B1E2B",
      "error": "#F27A7A",
      "error-texto": "#0B1E2B",
      "borde-campo": "#5F7789",
      "borde-suave": "#2A4256",
      "foco": "#00C9A7",
      "foco-halo": "#0B1E2B",
      "decorativo-advertencia": "#B7791F",
      "decorativo-borde": "#4F6677",
      "chip-neutro-texto": "#A9B7C2",
      "chip-neutro-fondo": "#1D3649",
      "chip-curso-texto": "#8CC4E6",
      "chip-curso-fondo": "#1D3649",
      "chip-cerrada-texto": "#4ADE80",
      "chip-cerrada-fondo": "#1D3649",
      "chip-riesgo-texto": "#E6B04A",
      "chip-riesgo-fondo": "#1D3649",
      "chip-vencida-texto": "#F27A7A",
      "chip-vencida-fondo": "#1D3649",
      "velo": "rgba(11, 30, 43, 0.6)"
  },
} as const;

export type NombreTema = keyof typeof temas;
export type NombreColor = keyof (typeof temas)['claro'];
